package pabloCuestaParcial2.apartado2;

/**
 * @author Pablo Cuesta Morer
 * @date 2023-04-26
 */
public enum ProvinciasEspana {
	ÁLAVA, ALBACETE, ALICANTE, ALMERÍA, ÁVILA, BADAJOZ, BARCELONA, BURGOS, CÁCERES, CÁDIZ, CASTELLÓN, CIUDAD_REAL,
	CÓRDOBA, CUENCA, GERONA, GRANADA, GUADALAJARA, GUIPÚZCOA, HUELVA, HUESCA, JAÉN, LA_CORUÑA, LA_RIOJA, LAS_PALMAS,
	LEÓN, LÉRIDA, LUGO, MADRID, MÁLAGA, MURCIA, NAVARRA, ORENSE, PALENCIA, PONTEVEDRA, SALAMANCA,
	SANTA_CRUZ_DE_TENERIFE, SEGOVIA, SEVILLA, SORIA, TARRAGONA, TERUEL, TOLEDO, VALENCIA, VALLADOLID, VIZCAYA, ZAMORA,
	ZARAGOZA
}
